services:
  postgres:
    image: postgres:16
    container_name: area-postgres
    restart: unless-stopped
    ports:
      - "8088:5432"
    env_file:
      - server/.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./server/db-data:/var/lib/postgresql/data
      - ./server/db-init:/docker-entrypoint-initdb.d
    networks:
      - area-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: area-server
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    env_file:
      - server/.env
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - area-net

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: area-web
    depends_on:
      - server
    ports:
      - "80:80"
    environment:
      # VITE_API_URL: "http://server:8080"
      VITE_API_URL: "http://localhost:8080"
    networks:
      - area-net

  mobile-apk-builder:
    build:
      context: ./mobile
      dockerfile: Dockerfile.apk-builder
    container_name: area-mobile-apk-builder
    networks:
      - area-net
    volumes:
      - ./mobile/apk-output:/app/build/app/outputs/flutter-apk

networks:
  area-net:
    driver: bridge